
name: Developer Setup
smtp:
  remote_server: smtp.qq.com:587
  workNumber: 10
  host: localhost
  port: 8080
  user: 1262193323@qq.com
  pwd: kwjklcboqznsbabc
imap:
  network: tcp
  remote_server: imap.qq.com:993
  workNumber: 10
  timeout: 120
  host: localhost
  port: 8080
  user: 1262193323@qq.com
  pwd: kwjklcboqznsbabc
mongo:
  url: mongodb://127.0.0.1:27017
  db: mail_go
  gridPrefix: mail_
