
host: localhost
port: 8080
name: Developer Setup
workNumber: 10
timeout: 1800
mail:
  user: 1262193323@qq.com
  pwd: kwjklcboqznsbabc
  smtp: smtp.qq.com:587
  imap: imap.qq.com:993
mongo:
  url: mongodb://127.0.0.1:27017
  db: mail_go
  gridPrefix: mail_
