
host: localhost
port: 8080
name: Developer Setup
redis:
  -
    host: 127.0.0.1:6379
    network: tcp
    name: key1

  - host: 127.0.0.1:6379
    network: tcp
    name: key2
mail:
  user: 1262193323@qq.com
  pwd: kwjklcboqznsbabc
  smtp: smtp.qq.com:587
  imap: imap.qq.com:993

#prod:
#  host: localhost
#  port: 8080
#  name: Developer Setup
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  mail:
#    user: 1262193323@qq.com
#    pwd: kwjklcboqznsbabc
#    smtp:
#      host: smtp.qq.com
#      port: 587
#      ssl: True
#    imap:
#      host: imap.qq.com
#      port: 993
#      ssl: False